name: Deploy to EC2
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd Audora
            git pull
            cd server && docker build -t audora-backend . && docker stop audora-backend || true && docker rm audora-backend || true && docker run -d --network host --name audora-backend audora-backend
            cd ../client && docker build -t audora-frontend . && docker stop audora-frontend || true && docker rm audora-frontend || true && docker run -d --network host --name audora-frontend audora-frontend